{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "react-native",
    "version": "0.70.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-debug.aar",
          "url": "react-native-0.70.6-debug.aar",
          "size": 32894488,
          "sha512": "379d8eed056115773866e61de3a637da1d56706c725c8293f442c9f972e16f54d82953f4e0c4ba274ce01ea895f984d569859218a03ef4f7f974927b5f5247d2",
          "sha256": "c27d12a4475a75b33f257ddc86e2d18d39ec922aba56cf6a3acb4af824d1678e",
          "sha1": "bcfd3631592a2df255c5968737d77d9cfeaad0a0",
          "md5": "b608e8c4c80c8f59d67b3f221b57696a"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-debug.aar",
          "url": "react-native-0.70.6-debug.aar",
          "size": 32894488,
          "sha512": "379d8eed056115773866e61de3a637da1d56706c725c8293f442c9f972e16f54d82953f4e0c4ba274ce01ea895f984d569859218a03ef4f7f974927b5f5247d2",
          "sha256": "c27d12a4475a75b33f257ddc86e2d18d39ec922aba56cf6a3acb4af824d1678e",
          "sha1": "bcfd3631592a2df255c5968737d77d9cfeaad0a0",
          "md5": "b608e8c4c80c8f59d67b3f221b57696a"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-native-0.70.6-debug-sources.jar",
          "url": "react-native-0.70.6-debug-sources.jar",
          "size": 1044883,
          "sha512": "eaf4c516f4665d611eae42e5a7f5c989be43f8844a92b04f223d3500d52be2cb430a215cf8fe57804e48320c92e52f45a8fab5870eb529c5b1bc9fed3b408768",
          "sha256": "42cc54a46131fc01de1661acc8e96dd65706d4febae9ad98903072de399dfb4f",
          "sha1": "08bff9fb912c617a0b765f1c8960651f47a27981",
          "md5": "e06c4c8b45e8cc55e672a5134471df3e"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-release.aar",
          "url": "react-native-0.70.6-release.aar",
          "size": 12613261,
          "sha512": "3818ca7ddc5eda6469db65e1f64ef03b9d3a8182879050aa990eea6d77a8f75ec065e3e97099d8f8af99392f7955e4c0597992d7632b706c54a3310a2ca1e086",
          "sha256": "21038e2d2c0fd08f97bcc8f7c94b322eb84e4dc0d3b554980d0a31082d843947",
          "sha1": "85954ddcacb020e98c346d01ea740327c39eded8",
          "md5": "9563b4941cb430cede008ef77606a4c7"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-release.aar",
          "url": "react-native-0.70.6-release.aar",
          "size": 12613261,
          "sha512": "3818ca7ddc5eda6469db65e1f64ef03b9d3a8182879050aa990eea6d77a8f75ec065e3e97099d8f8af99392f7955e4c0597992d7632b706c54a3310a2ca1e086",
          "sha256": "21038e2d2c0fd08f97bcc8f7c94b322eb84e4dc0d3b554980d0a31082d843947",
          "sha1": "85954ddcacb020e98c346d01ea740327c39eded8",
          "md5": "9563b4941cb430cede008ef77606a4c7"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-native-0.70.6-release-sources.jar",
          "url": "react-native-0.70.6-release-sources.jar",
          "size": 1044865,
          "sha512": "005013c88c953d2e145fd3acaf2efb9e83e24e4d7c0addade2678144f45de4b08e038b1a6742d5075f7c8aa373fa7a1fad26ac2b299fb64f4e397bd49be2651e",
          "sha256": "9b626ab057e72bb382ad1f9035e54a5cd860054d5298b8a8d0e911a0b0698fd0",
          "sha1": "0b8d9ae361178c2f31874cb6979f48a2c336964c",
          "md5": "e6e1a680f991e6fca49399bc4dd07563"
        }
      ]
    }
  ]
}
