{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "react-native",
    "version": "0.70.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-debug.aar",
          "url": "react-native-0.70.6-debug.aar",
          "size": 32894610,
          "sha512": "07833a6463b793806e0d1fc48b1eceded94f1a11881ba9b9bf59ec95a5ac80021f3458e4af473005561d2139c75e3cdc29ecfaecbb322fafe3d4c721f8cc4f03",
          "sha256": "fd8bbf1cb4abaa4c5ef0c0483972d0af86f401f3c1b9d4f2f5473049286b870e",
          "sha1": "f415ca2aee7b87f81c905cd4b5c02606e768087f",
          "md5": "7a8304048e028f1892ba2ce809460d63"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-debug.aar",
          "url": "react-native-0.70.6-debug.aar",
          "size": 32894610,
          "sha512": "07833a6463b793806e0d1fc48b1eceded94f1a11881ba9b9bf59ec95a5ac80021f3458e4af473005561d2139c75e3cdc29ecfaecbb322fafe3d4c721f8cc4f03",
          "sha256": "fd8bbf1cb4abaa4c5ef0c0483972d0af86f401f3c1b9d4f2f5473049286b870e",
          "sha1": "f415ca2aee7b87f81c905cd4b5c02606e768087f",
          "md5": "7a8304048e028f1892ba2ce809460d63"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-native-0.70.6-debug-sources.jar",
          "url": "react-native-0.70.6-debug-sources.jar",
          "size": 1044843,
          "sha512": "b76158c3e738736e416251d793457a40692f15c15d73ccdb27bb14c599aabefc6fab5137f0c9e644359bf0e571140c6d7e7557e5ce9848728e81ecb7d1d19b0e",
          "sha256": "9e56018da11825360e3d5478d13f3ace87ba0ac1bd01a83f92117ac92b574ce1",
          "sha1": "96d661d16b2844cde7d8de3e85c2d200d539f3b0",
          "md5": "cfa9261cec3b5d1868d28c49424a2da9"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-release.aar",
          "url": "react-native-0.70.6-release.aar",
          "size": 12613359,
          "sha512": "dd4d86894fc1a6b34fc9addb5018e1a4895699f09228f677f5096c9e31022071b17c63ac9ddb2438c7da202ed14d23066f8a4d784c60a361f4372de131953a20",
          "sha256": "2c51bc8b08f43b4a36f4b4e072572906806d787c2febd811c5c4a9e1a973418b",
          "sha1": "a29e8b6bbf39c2454fe923f7efb86e69acc1b1bc",
          "md5": "60a1e203ff373e26bc11527c0bbc25c6"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.70.6-release.aar",
          "url": "react-native-0.70.6-release.aar",
          "size": 12613359,
          "sha512": "dd4d86894fc1a6b34fc9addb5018e1a4895699f09228f677f5096c9e31022071b17c63ac9ddb2438c7da202ed14d23066f8a4d784c60a361f4372de131953a20",
          "sha256": "2c51bc8b08f43b4a36f4b4e072572906806d787c2febd811c5c4a9e1a973418b",
          "sha1": "a29e8b6bbf39c2454fe923f7efb86e69acc1b1bc",
          "md5": "60a1e203ff373e26bc11527c0bbc25c6"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "react-native-0.70.6-release-sources.jar",
          "url": "react-native-0.70.6-release-sources.jar",
          "size": 1044825,
          "sha512": "0062f31008be8ec2f574198eb3bea4bb24d87513a315db6afabf35ec3da4ba9d5afdb0f6194989930311fafd3c7553583941ca03bea835fa67ce5471a5904870",
          "sha256": "f154a6c2e7b82bc05739e2fd878ed56c4b4d6bec867f7a3733ac9087b9800cbc",
          "sha1": "c9cd174c71d80a229df1f2742ce1a3bf0595fcf1",
          "md5": "5130f1faa1d0bd87204ed36471d77c11"
        }
      ]
    }
  ]
}
