{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "hermes-engine",
    "version": "0.70.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.6-debug.aar",
          "url": "hermes-engine-0.70.6-debug.aar",
          "size": 114195264,
          "sha512": "8c0c5faf730bd39eb2e37278a75c0dfde773047fe77ebcea9ed789d6549f089729d8fedd01ee284b7131530bfb4c4f8a956c05f7c2bfc48e27d5d5d5e686b5e2",
          "sha256": "e8c06f51c8a06bc55c01236f9c8045632df796d81e30a526eff502655de6014a",
          "sha1": "4d64f11214a9775f32131cf7bed7fe470e6af656",
          "md5": "c97b2cddca36ec896caebe5fe8f2ac39"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.6-debug.aar",
          "url": "hermes-engine-0.70.6-debug.aar",
          "size": 114195264,
          "sha512": "8c0c5faf730bd39eb2e37278a75c0dfde773047fe77ebcea9ed789d6549f089729d8fedd01ee284b7131530bfb4c4f8a956c05f7c2bfc48e27d5d5d5e686b5e2",
          "sha256": "e8c06f51c8a06bc55c01236f9c8045632df796d81e30a526eff502655de6014a",
          "sha1": "4d64f11214a9775f32131cf7bed7fe470e6af656",
          "md5": "c97b2cddca36ec896caebe5fe8f2ac39"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.6-debug-sources.jar",
          "url": "hermes-engine-0.70.6-debug-sources.jar",
          "size": 62707,
          "sha512": "b6d659b87a103dd21026d8715420d047b70e76219d39121795598811cff2c7bb6cf3a860d8836fe6eeb753f785d7c2f7b961ea48c5cba27626a6e1cb5b07ee62",
          "sha256": "1fe6791aeefb0391d319d763c655a6f8232676141b886d0a467b8834a0b86497",
          "sha1": "75340c383a5d55a37d68181f12b1d8d939a3f065",
          "md5": "7b864274b543d21ee7d7c9c8e7f7b043"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.6-release.aar",
          "url": "hermes-engine-0.70.6-release.aar",
          "size": 99273584,
          "sha512": "7cf26b7f3dd82c30f9f47dae5e9984435e730d91e5baec23b52dac9bc3733b2399e2506dd3c2e7a4bd503b8ed5fd0b3f965b2f13a89c53ddd795ab6ba6855c66",
          "sha256": "949ba8bc89ba9f96103e7e27934df28be5eedb853303afed7550724ddff94040",
          "sha1": "5f943c79b4d490c1529b258e600baa3692cf366a",
          "md5": "df46bc117b8275a22bd8c48b1fc2e98c"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.6-release.aar",
          "url": "hermes-engine-0.70.6-release.aar",
          "size": 99273584,
          "sha512": "7cf26b7f3dd82c30f9f47dae5e9984435e730d91e5baec23b52dac9bc3733b2399e2506dd3c2e7a4bd503b8ed5fd0b3f965b2f13a89c53ddd795ab6ba6855c66",
          "sha256": "949ba8bc89ba9f96103e7e27934df28be5eedb853303afed7550724ddff94040",
          "sha1": "5f943c79b4d490c1529b258e600baa3692cf366a",
          "md5": "df46bc117b8275a22bd8c48b1fc2e98c"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.6-release-sources.jar",
          "url": "hermes-engine-0.70.6-release-sources.jar",
          "size": 62694,
          "sha512": "205a0fd395d6d02c27c4611ae1ceca7ccb4f3554f17f44d338f9ffef2e3521e933616e74ac1b17bb7d300891ede5ecf58e966a11becda27f6760f862f2316783",
          "sha256": "e622d9a7db5ba1a2161785ab8745dda58d1012aad04f7f9489fce207cf567f8a",
          "sha1": "34cf662170d553da87ddd8ef2213f13212955d1d",
          "md5": "c8db891c3be1b407d7079c02c303243b"
        }
      ]
    }
  ]
}
